approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableColors: true

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

enableTimers: true

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@cumulusds/*"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
