// flow-typed signature: e792e65cb8fca7e0419f55c2fad72458
// flow-typed version: <<STUB>>/git-describe_v^4.0.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-describe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-describe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-describe/lib/git-describe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-describe/index' {
  declare module.exports: $Exports<'git-describe'>;
}
declare module 'git-describe/index.js' {
  declare module.exports: $Exports<'git-describe'>;
}
declare module 'git-describe/lib/git-describe.js' {
  declare module.exports: $Exports<'git-describe/lib/git-describe'>;
}
