// flow-typed signature: 417d63fbe8bab7668f8d9d6603e3389e
// flow-typed version: <<STUB>>/@cumulusds/flow-coverage-report_v^0.0.2/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cumulusds/flow-coverage-report'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cumulusds/flow-coverage-report' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cumulusds/flow-coverage-report/assets/codemirror-annotatescrollbar-addon' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/codemirror-javascript-mode' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/codemirror-simplescrollbars-addon' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/codemirror' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/flow-highlight-source' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/index' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/jquery-3.1.0.min' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/semantic-tablesort' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/assets/semantic.min' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/bin/flow-coverage-report' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/cli/args' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/cli/config' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/cli/index' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-sourcefile' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-summary' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-head' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-row' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-meter-bar' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-summary-table' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/footer' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/head' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/components/html-report-page' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/flow' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/index' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/promisified' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/report-badge' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/report-html' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/report-json' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/dist/lib/report-text' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/cli/args' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/cli/config' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/cli/index' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/body-coverage-sourcefile' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/body-coverage-summary' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-head' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-row' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-meter-bar' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-summary-table' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/footer' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/head' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/components/html-report-page' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/flow' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/index' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/promisified' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/report-badge' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/report-html' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/report-json' {
  declare module.exports: any;
}

declare module '@cumulusds/flow-coverage-report/src/lib/report-text' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cumulusds/flow-coverage-report/assets/codemirror-annotatescrollbar-addon.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/codemirror-annotatescrollbar-addon'>;
}
declare module '@cumulusds/flow-coverage-report/assets/codemirror-javascript-mode.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/codemirror-javascript-mode'>;
}
declare module '@cumulusds/flow-coverage-report/assets/codemirror-simplescrollbars-addon.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/codemirror-simplescrollbars-addon'>;
}
declare module '@cumulusds/flow-coverage-report/assets/codemirror.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/codemirror'>;
}
declare module '@cumulusds/flow-coverage-report/assets/flow-highlight-source.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/flow-highlight-source'>;
}
declare module '@cumulusds/flow-coverage-report/assets/index.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/index'>;
}
declare module '@cumulusds/flow-coverage-report/assets/jquery-3.1.0.min.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/jquery-3.1.0.min'>;
}
declare module '@cumulusds/flow-coverage-report/assets/semantic-tablesort.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/semantic-tablesort'>;
}
declare module '@cumulusds/flow-coverage-report/assets/semantic.min.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/assets/semantic.min'>;
}
declare module '@cumulusds/flow-coverage-report/bin/flow-coverage-report.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/bin/flow-coverage-report'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/cli/args.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/cli/args'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/cli/config.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/cli/config'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/cli/index.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/cli/index'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-sourcefile.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-sourcefile'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-summary.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/body-coverage-summary'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-head.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-head'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-row.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/coverage-file-table-row'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-meter-bar.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/coverage-meter-bar'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/coverage-summary-table.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/coverage-summary-table'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/footer.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/footer'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/head.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/head'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/components/html-report-page.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/components/html-report-page'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/flow.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/flow'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/index.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/index'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/promisified.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/promisified'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/report-badge.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/report-badge'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/report-html.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/report-html'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/report-json.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/report-json'>;
}
declare module '@cumulusds/flow-coverage-report/dist/lib/report-text.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/dist/lib/report-text'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/cli/args.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/cli/args'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/cli/config.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/cli/config'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/cli/index.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/cli/index'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/body-coverage-sourcefile.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/body-coverage-sourcefile'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/body-coverage-summary.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/body-coverage-summary'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-head.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-head'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-row.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/coverage-file-table-row'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-meter-bar.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/coverage-meter-bar'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/coverage-summary-table.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/coverage-summary-table'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/footer.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/footer'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/head.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/head'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/components/html-report-page.jsx' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/components/html-report-page'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/flow.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/flow'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/index.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/index'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/promisified.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/promisified'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/report-badge.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/report-badge'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/report-html.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/report-html'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/report-json.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/report-json'>;
}
declare module '@cumulusds/flow-coverage-report/src/lib/report-text.js' {
  declare module.exports: $Exports<'@cumulusds/flow-coverage-report/src/lib/report-text'>;
}
